package com.lucifer.electronics.store.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

@Component
public class JwtHelper {

//  Token validity duration
    public static final long JWT_TOKEN_VALIDITY = 5 * 60 * 60;

//  This will be encoded when JWT will get created i.e. this secret will be used to generate JWT token.
    @Value("${jwt.secret}")
    private String secret;

//  Retrieve username from jwt token
    public String getUsernameFromToken(String token) {
        return getClaimFromToken(token, Claims::getSubject);
    }

//  Retrieve expiration date from jwt token
    public Date getExpirationDateFromToken(String token) {
        return getClaimFromToken(token, Claims::getExpiration);
    }

    /**
     * This method retrieves a specific claim from a JWT (JSON Web Token) by applying a function to the claims contained within the token
     *
     * @param token:         A string representing the JWT token from which to extract the claim.
     * @param claimsResolver - A Function that takes Claims as input and returns a value of type T.
     *                       This function is responsible for extracting the specific claim from the JWT.
     * @return: Result of applying the claimsResolver function to the claims object.
     *
     * What are JWT Claims? - https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims
     * Claims are pieces of information contained within the JWT payload, such as user roles, permissions, or other relevant data.
     */
    public <T> T getClaimFromToken(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = getAllClaimsFromToken(token);
        return claimsResolver.apply(claims);
    }

//  To retrieve any information from token we will need the secret key
    private Claims getAllClaimsFromToken(String token) {
        return Jwts.parser().setSigningKey(secret).parseClaimsJws(token).getBody();
    }

//  Check if the token has expired
    private Boolean isTokenExpired(String token) {
        final Date expiration = getExpirationDateFromToken(token);
        return expiration.before(new Date());
    }

    /**
     *
     * @param userDetails -  UserDetails object representing the authenticated user as input
     * @return - JWT generated by the doGenerateToken() method.
     */
    public String generateToken(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        return doGenerateToken(claims, userDetails.getUsername());
    }

//  While creating the token -
//  1. Define  claims of the token, like Issuer, Expiration, Subject, and the ID
//  2. Sign the JWT using the HS256 algorithm and secret key.
//  3. According to JWS Compact Serialization (https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-3.1)
//  Compaction of the JWT to a URL-safe string

    /**
     * This method encapsulates the logic for generating a JWT with the specified claims and subject,
     * including issuance and expiration times, and signing the token with a secret key using the HS256 algorithm.
     *
     *
     */
    private String doGenerateToken(Map<String, Object> claims, String subject) {
        return Jwts.builder()
                .setClaims(claims) // Setting claims as the payload of the JWT.
                .setSubject(subject) // Setting subject (which is typically the username) as the subject of the JWT.
                .setIssuedAt(new Date(System.currentTimeMillis())) // Setting current time.
                .setExpiration(new Date(System.currentTimeMillis() + JWT_TOKEN_VALIDITY * 1000)) // Setting expiration time specified by JWT_TOKEN_VALIDITY.
                .signWith(SignatureAlgorithm.HS256, secret) // Finally signing the token with HS256 (HMAC SHA-256) signature algorithm using a secret key (the "secret" variable).
                .compact(); // Compacting into a string representation of the JWT.
    }

    /**
     * This method provides a simple validation mechanism for JWTs by comparing the username extracted from the
     * token with the username from the UserDetails object and checking if the token has expired. If both checks pass,
     * the token is considered valid.
     */
    public Boolean validateToken(String token, UserDetails userDetails) {
        final String username = getUsernameFromToken(token);
        return (username.equals(userDetails.getUsername()) && !isTokenExpired(token));
    }
}
